### ISSUE TITLE
Not getting any data while connecting ultrasonic sensor directly to Jetson Nano

### ISSUE THREAD

**Issue by udaysaikrishna** [AnbuKumar-maker/Radar-Scan-and-Object-Distance-Detection-using-JetsonNano#1]
I connected the ultrasonic sensor to my Jetson Nano board. But I am not getting any data from it. 

Did you interface Radar, Ultrasonic to Arduino?

Is that the only way or can we use Jetson Nano itself?

**Comment by AnbuKumar-maker** [comment]
Can you share the pin diagram ?

Regards
RoboThoughts AI Services Pvt Ltd

**Comment by udaysaikrishna** [comment]
![images](https://user-images.githubusercontent.com/20275035/93367866-ba0f2d00-f86a-11ea-9e0a-d816acc92405.png)

Please find the attached pin diagram of Jetson Nano. I am using Pin32 and Pin33 for connecting Trig and echo.

**Comment by AnbuKumar-maker** [comment]
Did you install the Python library for US sensor and import into the IDE ?

Regards
RoboThoughts AI Services Pvt Ltd

**Comment by udaysaikrishna** [comment]
No. I am using jetson.GPIO library only.
Is there any library we should add?

**Comment by AnbuKumar-maker** [comment]
Then it should work, what error do you see ?

Regards
RoboThoughts AI Services Pvt Ltd

**Comment by udaysaikrishna** [comment]
I am not getting any errors. just not receiving any data.
When I check the voltage after making the GPIO pin High. It should show 3.3v. but it is showing 0v.

So, I believe it must be some GPIO configuration issue.

Here are my connections:

Jetson Nano             Ultrasonic Sensor

5v                                 VCC
GPIO50                        TRIG
GPIO79                        ECHO
GND                            GND

Here is my code.

```
import Jetson.GPIO as GPIO
import time

#Setting the GPIO Mode
GPIO.setmode(GPIO.BCM)

#Declaring the GPIO Pins
TRIG = 11
ECHO = 12
i=0

#Setting the GPIO Pin STAT
GPIO.setup(TRIG,GPIO.OUT)
GPIO.setup(ECHO,GPIO.IN)

GPIO.output(TRIG, False)
print("Calibrating.....")

time.sleep(2)

print("Place the object......")

try:

    while True:
       GPIO.output(TRIG, True)
       time.sleep(0.00001)
       GPIO.output(TRIG, False)

       while GPIO.input(ECHO)==0:
          pulse_start = time.time()

       while GPIO.input(ECHO)==1:
          pulse_end = time.time()

       pulse_duration = pulse_end - pulse_start

       distance = pulse_duration * 17150
       distance = round(distance+1.15, 2)

        if distance<=20 and distance>=5:
          print(f"distance: {distance} cm")
          i=1 

       if distance>20 and i==1:
          print("place the object....")
          i=0

       time.sleep(2)

except KeyboardInterrupt:
     GPIO.cleanup()
```

**Comment by AnbuKumar-maker** [comment]
Yes its clearly an issue with GPIO output signal 

Regards
RoboThoughts AI Services Pvt Ltd

**Comment by udaysaikrishna** [comment]
Do you have any idea about how to enable GPIO or powering up GPIO? Please let me know.

**Comment by AnbuKumar-maker** [comment]
Have you figured out the issue ? I could see that you are not getting proper signal output from GPIO, I had the same issue long back when I started with Jetson Nano, later I figured out how to use BC547 or PN2222 Transistor to amplify the signal from the GPIO pin. Give a try by adding a transistor. See details in this article https://www.acmesystems.it/HC-SR04

**Comment by udaysaikrishna** [comment]
I have figured out the issue. Just made a small mistake. I used GPIO.BCM for board pins instead of GPIO.BOARD. 

Thanks for the help though.

**Comment by udaysaikrishna** [comment]
I am having another issue with Optical Flow sensor (PMW3901). I am getting error while running the code like "No device Found".
